---
version: '2'
services:

  zookeeper:
    image: 'confluentinc/cp-zookeeper:5.5.1'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: 'confluentinc/cp-kafka:5.5.1'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  demo-producer:
    image: demo-producer:latest
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    environment:
      KAFKA_SERVERS: kafka:29092

  demo-consumer:
    image: demo-consumer:latest
    depends_on:
      - kafka
    ports:
      - '8081:8081'
    environment:
      KAFKA_SERVERS: kafka:29092